---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  labels: 
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bggdb-po
  template:
    metadata:
      name: bggdb-po
      labels:
        name: bggdb-po
    spec:
      containers:
      - name: db-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3306
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mydb-svc
  labels:
    name: db-svc
spec:
  type: ClusterIP
  selector:
    name: bggdb-po
  ports:
  - port: 3306 # service port
    targetPort: 3306 # pod port = container port
